### ISSUE TITLE
Why deeperCopyVideoSampleBuffer in CaptureVideoPreview?

### ISSUE THREAD

**Issue by kisso** [MyCometG3/DLABCaptureManager#5]
hello, i have question why is necessary to make deep copy of sampleBuffer from device? why just not pass it directly? wouldn't be it more effective?

**Comment by MyCometG3** [comment]
I understand it is inefficient. It is because of a few minor issue.

The CMSampleBuffer itself and QuickTime Movie format have some feature to support clean aperture (as tapt/clap atom), but there are some clap related buggy behavior left in multiple macOS frameworks (while moving from QuickTime into CoreMedia). For example, AVSampleBufferDisplayLayer and GPU world do not accept CMSampleBuffer with clap atom. AVAssetWriter could produce broken track aperture (as tapt atom) with clap CMSampleBuffer (AFAIK uncompressed buffer only).

While debugging such scenario, (for example: reassembling CMFormatDescription etc.) I would prefer deep-copied CMSampleBuffer to make them independent b/w display task and writing task to avoid such buggy issues.

If you do not need to consider clean aperture source like Cam output, or SD stream etc. then I guess you could ignore and skip such inefficient operation.
