### ISSUE TITLE
cannot get time code

### ISSUE THREAD

**Issue by kisso** [MyCometG3/DLABCaptureManager#6]
hi, I am not able get timecode from video.
DLABriding is always callling 

`public func processCapturedVideoSample(_ sampleBuffer: CMSampleBuffer,
                                           of sender:DLABDevice)` callback instead of

`public func processCapturedVideoSample(_ sampleBuffer: CMSampleBuffer,
                                           timecodeSetting setting: DLABTimecodeSetting,
                                           of sender:DLABDevice)`

can you please help me how to receive a time code?

have a good day

**Comment by MyCometG3** [comment]
Thank you for reporting this issue.

I found that a logic bug in DLABridging/DLABDevice+Input.mm line 563-564, where 
"self.outputVideoSetting.xx" should be "self.inputVideoSetting.xx"

Would you please try with above changes applied and verify if it works?
I would apply these update in later version.

NOTE: For SD capture, videoSetting.useVITC is true, and For HD capture useRP188 is true.


```
- (DLABTimecodeSetting*) createTimecodeSettingOf:(IDeckLinkVideoInputFrame*)videoFrame
{
    NSParameterAssert(videoFrame);
    
    // Check videoFrame
    DLABTimecodeSetting* setting = nil;
    
    BOOL useVITC = self.outputVideoSetting.useVITC; ###### should be inputVideoSetting
    BOOL useRP188 = self.outputVideoSetting.useRP188; ###### should be inputVideoSetting
:
```

**Comment by kisso** [comment]
Thank you, I will try it next week, because I don't have hardware here.

**Comment by kisso** [comment]
Yeah I fixed it, now it's callling `public func processCapturedVideoSample(_ sampleBuffer: CMSampleBuffer,
                                           timecodeSetting setting: DLABTimecodeSetting,
                                           of sender: DLABDevice)`

but when I do print: 
```
print(timecodeSampleBuffer.decodeTimeStamp)
print(timecodeSampleBuffer.outputDecodeTimeStamp)
print(timecodeSampleBuffer.presentationTimeStamp)
print(timecodeSampleBuffer.outputPresentationTimeStamp)
```

I got always zero. I need this to work, because I want to use multiple video streams and try to synchronize them.

**Comment by MyCometG3** [comment]
Thank you. I need to fix DLABTimecodeSetting -createTimecodeSampleIn:videoSample:.
It uses null timingInfo instead of info from Video sample.
I will apply w/ new commit(s) later.

`        // Extract timeingInfo from videoSample
        CMSampleTimingInfo timingInfo = {0};
        CMSampleBufferGetSampleTimingInfo(videoSampleBuffer, 0, &timingInfo);
`

`        // Create new sampleBuffer
        CMSampleTimingInfo timingInfoTMP = {0};
        status = CMSampleBufferCreate(kCFAllocatorDefault,
                                      dataBuffer,
                                      true,
                                      NULL,
                                      NULL,
                                      description,
                                      1,
                                      1,
                                      &timingInfoTMP,
                                      1,
                                      &sizes,
                                      &sampleBuffer);
`

**Comment by kisso** [comment]
now it works thank you, please which one data would you use to sync videos?
```
timecodeSampleBuffer.decodeTimeStamp
timecodeSampleBuffer.outputDecodeTimeStamp
timecodeSampleBuffer.presentationTimeStamp
timecodeSampleBuffer.outputPresentationTimeStamp
```

**Comment by MyCometG3** [comment]
PresentationTimeStamp is to sync. In this framework every video sample do not use reorder.

NOTE: for compressed video stream like AVC coding it will reorder samples depends on type. Only such stream use decode timestamp with presentation timestamp.

**Comment by kisso** [comment]
it's working I do have 4 instances of DLABCaptureManager, and in 
```
func processCapturedVideoSample(_ sampleBuffer: CMSampleBuffer,
                                           timecodeSetting setting: DLABTimecodeSetting,
                                           of sender: DLABDevice)
```

I write only frames from specific timecode, this way I synchronize the start of video, but I don't know how to sync audio because in
```
public func processCapturedVideoSample(_ sampleBuffer: CMSampleBuffer,
                                           of sender: DLABDevice)
```
I don't receive any timecode.

What do you think, is it possible to sync video and audio entirely without timecode? because in some type of cameras we don't have timecode.

**Comment by MyCometG3** [comment]
Every CMSampleBuffer has presentation timestamp. Each Video/Audio/Timecode (now) uses same timeline.
After you put every sample into single QuickTime Movie container, actual sync b/w each media track is managed via movie object.

**Comment by kisso** [comment]
But for example I have 4 cameras and I need to create 4 separate videos with same length at same time.

**Comment by MyCometG3** [comment]
OK, now your concern is on multi-device-capture-on-single-Mac-single-app, correct?

In short current version of DLABCaptureManager itself does not work in synchronized capture; no multiple instances support nor co-operative capture.
Main reason is simply I do not have such device (multiple input with synchronized capture feature).
But I can tell you from the API design issue side.

Please see SDK pdf - 2.4.13.1 Synchronized Capture.

> — An application performing synchronized capture should perform the following steps: For each device to synchronize for capture.
> — Call IDeckLinkProfileAttributes::GetFlag with the BMDDeckLinkSupportsSynchronizeToCaptureGroup flag to check that the DeckLink hardware supports grouping for synchronized capture.

Verify all of DLABDevice if device supports capturegroup feature using:
: DLABDevice - (NSNumber*) boolValueForAttribute:(DLABAttribute) attributeID error:(NSError**)error
: BMDDeckLinkAttributeID => DLABDeckLinkAttributeID
: BMDDeckLinkSupportsSynchronizeToCaptureGroup(Flag) => DLABAttributeSupportsSynchronizeToCaptureGroup(bool)

> — Call IDeckLinkConfiguration::SetInt with the bmdDeckLinkConfigCaptureGroup configuration ID, along with a common integer value for the capture group. This setting is persistent until system reboot. 

Assign "shared" group value on "every" DLABDevice using:
: DLABDevice - (BOOL) setIntValue:(NSInteger)value forConfiguration:(DLABConfiguration) configurationID error:(NSError**)error
: BMDDeckLinkConfigurationID => DLABConfiguration
: bmdDeckLinkConfigCaptureGroup(Int64) => DLABConfigurationCaptureGroup(Int64)

> — Obtain IDeckLinkInput interface and enable each input in the capture group.
> — IDeckLinkInput::EnableVideoInput, with the bmdVideoInputSynchronizeToCaptureGroup flag.
> — IDeckLinkInput::EnableAudioInput

DLABCaptureManager.inputFlag with DLABVideoInputFlagSynchronizeToCaptureGroup need to be set.
NOTE: DLABCaptureManger.captureStart() does most of above, but need to modify skipping the last part "try device.startStream()". 

> — IDeckLinkInput::SetCallback
> — For each input in the capture group, call IDeckLinkStatus::GetFlag with the bmdDeckLinkStatusVideoInputSignalLocked status ID to ensure that the input is locked.

NOTE: this feature is not available in DLABCaptureManager. You need to modify DLABCaptureManger.captureStart().

> — To start the synchronized capture call IDeckLinkInput::StartStreams on any input device in the group. 

NOTE: Instead of DLABCaptureManger.captureStart(), you need to run device.startStreams() by yourself, on one of input device only.

> — To stop synchronized capture, call IDeckLinkInput::StopStreams on any input device in the group.

NOTE: You need to modify "try device.stopStreams()" only issued to one of inputdevice.

**Comment by kisso** [comment]
This is for synchronized capture, but how to sync writer? I mean guarantee for all recorded videos same length and time.

**Comment by MyCometG3** [comment]
If all of devices support Synchronized Capture, every device produce first video sample at exactly same time stamp. (in other words, Movie 1 first Video Sample 00:00:00:00 == Movie 2 first Video sample 00:00:00:00, ...)

At end of capture, some device may produce extra sample though, you can calculate each accumulated sample duration for each devices and also number of Video samples. After finalizing each AVMovie into file(s), reopen them and validate each Movie, truncate to shortest one.

Truncating multiple movie file into exact same duration is tricky. And if your video source runs in different time resolution (for example one is in 29.97 fps, other are in 30.0 fps), last video sample could be truncated into less than one frame.

I hope this could be the answer to your question.

**Comment by kisso** [comment]
oh this sounds good, and the very last question is, if I can make this synchronized capture without external clocks?

**Comment by MyCometG3** [comment]
Strictly, I believe external clock is mandatory for professional capture. Such like SMPTE multiplier for HDMI stream, etc.

If such strict synchronized capture is not required, I guess you can compose each QuickTime Movie using some Video editor application like iMovie or Final Cut Pro X.

**Comment by kisso** [comment]
My use case is: record 4 videos with my app and after that play those 4 videos in my app at same time without any offset

**Comment by MyCometG3** [comment]
> play those 4 videos in my app at same time without any offset

I guess you want to play multiple AVMovie on multiple DeckLink Devices.
Please see SDK pdf - 2.4.13.2 Synchronized Playback.

NOTE: for simple playback, DLABridging - Issue #1 may help. You also need to provide master clock to play each stream in-sync.
NOTE: DLABCaptureManager itself does not have any playback feature so you need to write your own code to do so.

**Comment by kisso** [comment]
No no, I need to play 4 recorded movies in my app window.

**Comment by MyCometG3** [comment]
Well, Playback AVMovie in application is not covered in this framework.

For synchronizing AVPlayer WWDC 2012-517 could meet your request. Preroll AVPlayer syncing on custom timeline.
https://developer.apple.com/videos/play/wwdc2012/517/
https://developer.apple.com/devcenter/download.action?path=/videos/wwdc_2012__hd/session_517__realtime_media_effects_and_processing_during_playback.mov

I think I can close this issue because it is now out of scope from this framework feature. Please confirm.

**Comment by kisso** [comment]
I confirm, you can close thank you so much
