### ISSUE TITLE
Why did you decide to use core animation for video preview?

### ISSUE THREAD

**Issue by kisso** [MyCometG3/DLABCaptureManager#7]
Hi, can you please describe me why did you implement rendering video in Core Animation instead of Metal? Wouldn't be more effective do render it with GPU?

**Comment by MyCometG3** [comment]
AFAIK, CALayer rendering runs in GPU world.

AVSampleBufferDisplayLayer provides intelligent buffer queuing/timing control/color sync ready, and also using CALayer I can easily implement strict aspect ratio preserving rendering. That is my main purpose to create this class instead of DeckLinkAPI based preview implementation.

I am not sure if AVSampleBufferDisplayLayer works on MTKView. Do you have any idea?
